### PR TITLE
Opt-in to find main branches

### PR DESCRIPTION
**Pull request by jni**
Finding main branches is expensive. This PR makes it opt-in in the summarize function.

### CODE REVIEW

**Comment by jni** [comment]
@kevinyamauchi are you ok with this change? On this laptop, for the test skeleton in `benchmarks/`, summarize takes 792s, of which 20ms is everything *other* than find_main_branches. :joy:

**Review by kevinyamauchi — COMMENTED** [review]
Looks good to me! I knew `find_main_branches` was slow, but I didn't realize it was that slow, haha.

The failed tests look unrelated to me (timing of a different function), but I don't know them well enough to say for sure.

**Comment by jni** [comment]
Yeah, some of the tests need tweaking, plus windows and mac are broken for unrelated reasons. Just wanted to make sure I wasn't breaking something you were relying on for your upcoming paper.

**Comment by kevinyamauchi** [comment]
> Yeah, some of the tests need tweaking, plus windows and mac are broken for unrelated reasons. Just wanted to make sure I wasn't breaking something you were relying on for your upcoming paper.

Thanks for checking in! All good from that perspective.

**Pull request merged**
