### PR TITLE
Use minimum spanning tree to simplify junctions

### LINKED ISSUE #133: Idea: don't collapse junction pixels
I've referred people to the junction-handling in skan from the paper's supplementary material more times than I can remember:

https://peerj.com/articles/4312/#supp-1

It's a rather confusing part of the code, and though it is useful, it would be good to have alternatives that preserve each and every pixel in the original skeleton.

One idea: of all the pixels in a junction, only assign *one* to be a junction (how to do that is left as an exercise for the reader). The others get assigned to the incoming paths, and all links to non-junction pixels are removed (ie the degrees are artificially reduced).

### PR DESCRIPTION
**Pull request by jni**
Closes #133

Joint work with @kevinyamauchi

- Add function to use MST on junctions
- Add minimum spanning tree junction mode

This has the added benefit of doing true pruning on the graph.

### CODE REVIEW

**Comment by jni** [comment]
btw @kevinyamauchi is your skan plugin published? Now that we have this it would be super awesome to test interactively on real skeletons!

**Comment by kevinyamauchi** [comment]
@marlene09 and I haven't published the plugin we are making on pypi yet. However, it's available here: https://github.com/kevinyamauchi/napari-skeleton-curator. We are currently working on a widget for interactive pruning (2D and 3D) on the `add-pruning-widget` branch (sorry, no real docs yet).

**Comment by jni** [comment]
CI failures are unrelated to the PR, I'm gonna merge! I'll do a bit of API cleanup in a follow-up PR and then release 0.10! 🎉

**Comment by jni** [comment]
@kevinyamauchi None of my plugins are documented *at all*. It's bad 😂 but kind of inevitable... napari plugins is such a [blue ocean](https://en.wikipedia.org/wiki/Blue_Ocean_Strategy) right now! 🎉

**Pull request merged**
