### PR TITLE
Drop Python 3.7 support

### LINKED ISSUE #165: Drop Py 3.7 support
Python 3.7 builds are failing because most of our dependencies have already dropped support according to NEP-29 the NumPy deprecation policy. We should just drop ours too.

### PR DESCRIPTION
**Pull request by kushaangupta**
Closes #165

### CODE REVIEW

**Comment by jni** [comment]
Thanks @kushaangupta! We should also:
- add 3.10 to the list
- update the test builds in `.github/workflows` to not build 3.7 and build 3.10.

**Comment by kushaangupta** [comment]
Weirdly, the workflow job is interpreting 3.10 as 3.1 leading to the failures.

**Comment by jni** [comment]
Ah yes this was a common error, you need to write "3.10" in quotes so that it is interpreted as a string rather than a float.

**Comment by jni** [comment]
Thank you! :blush:

**Pull request merged**
