### PR TITLE
add path pruning, __array__ method, and longest shortest branch detection to Skeleton

### PR DESCRIPTION
**Pull request by kevinyamauchi**
This PR adds the ability to prune paths from a `Skeleton`. We have additionally added a utility function to determine which paths are part of a main branch of a skeleton (i.e., have the longest, shortest path).

### CODE REVIEW

**Comment by jni** [comment]
Looks like something went wrong with the merge, @kevinyamauchi! Tests are failing with:

```
    from .nputil import pad, raveled_steps_to_neighbors
```

pad was removed in favour of np.pad (which did not exist when this lib was written!). I think if you can remove that import we should be golden!

**Comment by kevinyamauchi** [comment]
Done!

**Comment by kevinyamauchi** [comment]
Currently, there are a couple of caveats to this PR that are related to how junctions are currently represented (https://github.com/jni/skan/issues/133):
- the junction pixels in the label image that is generated by the `Skeleton.__array__` method may have their own unique label value.
- the `Skeleton.prune` method can leave one pixel behind from the pruned branch at the junction from which the branch was pruned.

For the pruning issue, since we know the junction at which the pruning has occurred, we can likely fix the artifacts. Additionally, there may be some ideas [here](https://en.wikipedia.org/wiki/Pruning_(morphology)) for cleaning up the pruning site.

**Comment by jni** [comment]
Thanks @kevinyamauchi! The failing CI has nothing to do with this PR:

- Windows failure is known, see #130 
- Ubuntu *just* failed on a timing test, probably just due to random fluctuations in the VM load.
- macOS failed because of some environment activation issues (matplotlib not found, even though it is installed). @NelleV was telling me about similar issues in her own CI, though she didn't have a satisfying resolution (move the testing to a bash script 😬). Anyway, we'll investigate after this PR.

**Pull request merged**
