### PR TITLE
DOC Add versions to documentation

### PR DESCRIPTION
**Pull request by lucyleeow**
Aims to build document for all tagged versions and add versions to sidebar of documentation.

Outlines steps required: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions

First attempt tries using [sphinx-multiversion](https://holzhaus.github.io/sphinx-multiversion/master/quickstart.html) (as easier than writing all code our self). Note although this project has not seen much activity recently, see [this comment from the author](https://github.com/sphinx-contrib/sphinxcontrib-versioning/pull/78#issuecomment-599193860).

### CODE REVIEW

**Comment by lucyleeow** [comment]
To build with sphinx multiversion:
```
# Without sphinx-multiversion
sphinx-build docs build/html

# With sphinx-multiversion
sphinx-multiversion docs build/html
```
I am not sure if I should alter the current make file to have a 'make normal' and 'make multiversion' or just update the workflow yml to the multiversion. If the latter, I am not sure what the syntax `@` means in `@NAPARI_APPLICATION_IPY_INTERACTIVE=0`

**Comment by lucyleeow** [comment]
Is there a way to tell if the docs are building via the CI .. ?

**Comment by jni** [comment]
For some reason, the docs builds aren't happening in this PR. You can see in #171, if you click on the green tick mark, the top action is "build docs" and you can click on it and view the artifact. In this PR, I think maybe the changes you've made to build-docs.yml may have made it a malformed yaml? The `@` in that string is actually Makefile syntax and should be removed here.

**Comment by jni** [comment]
Also, @lucyleeow, now that the pydata theme has good versioning support, maybe we just switch the theme and use the pydata version switcher?

**Comment by lucyleeow** [comment]
Closed in favour of  #173

**Pull request closed without merging**
